mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('oda.urls')),
    
    
]

oda/urls.py
from django.urls import path,re_path
from . import views
from django.conf.urls import url

app_name='oda'
urlpatterns = [
    #path('brand/<int:brand_id>/', views.brand_data, name='brand_data'),
    path('user/driver/',views.driver_data,name='driver_data'),
    path('user/',views.login_user,name='login'),
    path('user/heatmap/',views.Posdata_brand,name='brand_posdata'),
    path('driver/heatmap/<int:driver_id>/',views.Posdata_driver,name='driver_posdata'),
    path('',views.Home,name='home')
]

oda/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.conf import settings

class Wraptype(models.Model):
	wrap_type=models.CharField(max_length=20)
	price=models.IntegerField()
	def __str__(self):
		return self.wrap_type

class Brand(models.Model):
	manager=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	wrap_type=models.ForeignKey('Wraptype',on_delete=models.PROTECT)
	name=models.CharField(max_length=50)
	no_of_cars=models.IntegerField()
	region=models.CharField(max_length=50)
	duration=models.IntegerField()
	start_date=models.DateField()
	def __str__(self):
		return self.name

class Car_model(models.Model):
	car_model=models.CharField(max_length=20) 
	def __str__(self):
		return self.car_model

class Driver(models.Model):
	driver_name=models.CharField(max_length=50)
	car_model=models.ForeignKey('Car_model',on_delete=models.PROTECT)
	brand=models.ForeignKey('Brand',on_delete=models.PROTECT)
	car_no=models.CharField(max_length=20)
	phone_no=PhoneNumberField(null=False,blank=False)
	def __str__(self):
		return self.driver_name
# Create your models here.
class Pos_data(models.Model):
	brand=models.ForeignKey('Brand',null=True,on_delete=models.SET_NULL)
	driver=models.ForeignKey('Driver',null=True,on_delete=models.SET_NULL)
	latpos=models.FloatField()
	lonpos=models.FloatField()

oda/forms.py
from django.contrib.auth.models import User
from django import forms

class Userform(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model=User
		fields=['username','password']

oda/views.py
from django.shortcuts import render,get_object_or_404
from .models import Brand,Driver,Pos_data

from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login

from .serializers import PosdataSerializer

# Create your views here.


# this can be also done brand.driver_set

def driver_data(request):
	if not request.user.is_authenticated:
		return render(request, 'oda/login.html')
	else:
		brand=get_object_or_404(Brand,manager=request.user)
		driver_data=brand.driver_set.all()
		context={'driver_data':driver_data}
		return render(request,'oda/driver_data.html',context)


def login_user(request):
	if request.method=="POST":
		username=request.POST['username']
		password=request.POST['password']
		user=authenticate(username=username,password=password)
		if user is not None:
			if user.is_active:
				login(request,user)
				brand_data=get_object_or_404(Brand,manager=request.user)
				#brand_data=Brand.objects.filter(manager=request.user)
				return render(request,'oda/brand_data.html',{'brand_data':brand_data})
				
			else:
				return render(request,'oda/login.html',{'error_message':"your account has been disabled"})
		else:
			return render(request,'oda/login.html', {'error_message':"invalid login Credentials"})
	else:
		if request.user.is_anonymous:
			return render(request,'oda/login.html')
		else:
			brand_data=Brand.objects.filter(manager=request.user)
			if not brand_data:
				return render(request,'oda/login.html')
			else:
				return render(request,'oda/brand_data.html',{'brand_data':brand_data})
			

def Posdata_brand(request):
	if not request.user.is_authenticated:
		return render(request, 'oda/login.html')
	else:
		brand=get_object_or_404(Brand,manager=request.user)
		posdata=Pos_data.objects.filter(brand=brand)
		serializer=PosdataSerializer(posdata,many=True)
		data=serializer.data[:]
		return render(request,'oda/map_point.html',{'data':data})

def Posdata_driver(request,driver_id):
	if not request.user.is_authenticated:
		return render(request, 'oda/login.html')
	else:
		posdata=Pos_data.objects.filter(driver_id=driver_id)
		serializer=PosdataSerializer(posdata,many=True)
		data=serializer.data[:]
		return render(request,'oda/map_point.html',{'data':data})

def Home(request):
	return render(request,'oda/home.html',{})

'''

def brand_data(request,brand_id):
	brand_data=get_object_or_404(Brand,pk=brand_id)
	context={'brand_data':brand_data}
	return render(request,'oda/brand_data.html',context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return return redirect('oda:brand_data')
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
	return render(request, 'music/login.html')

class UserFormView(View):
	form_class=Userform
	template_name='oda/registration_form.html'

	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})
	#process form data
	def post(self,request):
		form=self.form_class(request.POST)

		if form.is_valid():
			user=form.save(commit=False)
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			
			#user.set_password(password)
			#user.save()
			
			#return user object if credential are corect
			user = authenticate(username=username,password=password)
			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect('oda:brand_data 2')
				else:
					return render(request,self.template_name,{'form':form,'error_message':"user not active"})		
			context={'form':form,'error_message':"credential not valid1"}
			return render(request,self.template_name,context)
				#request.user.username
			
		else:
			context={'form':form,'error_message':"credential not valid2"}
			return render(request,self.template_name,context)
'''

oda/templates/oda/brand_data.html
<html>
	<h1>Campaign Detail of {{brand_data.name}}</h1>
	 <ul style="list-style-type:disc">
	  <li>Campaign Region: {{brand_data.region}} </li>
	  <li>Wrap type chosen: {{brand_data.wrap_type.wrap_type}}</li>
	  <li>Campaign Start date: {{brand_data.start_date}}</li>
	  <li>Campaign Duration: {{brand_data.duration}}</li>
	  <li> <a href="{%url 'oda:driver_data' %}">Driver Detail</a></li>
	  <li>Distance covered: ^\()/^</li>
	  <li><a href="{%url 'oda:brand_posdata'%}">Campaign heat map</a></li>
	</ul>

</html>

oda/templates/oda/driver_data.html
<html>
	<h1>Details of campaign drivers</h1>
	{%for dat in driver_data%}
	<h1>---------------------------------</h1>
	<ul style="list-style-type:disc">
	<li>Name={{dat.driver_name}}</li>
	<li>Car Model={{dat.car_model.car_model}}
	<li>Phone_NO={{dat.phone_no}}</li>
	<li>Distance Covered=^\()/^
	<li><a href="{%url 'oda:driver_posdata' dat.pk%}">driver heat Map</a></li>
	</ul>
	<h1>---------------------------------</h1>
	{%endfor%}
</html>

oda/templates/oda/home.html
<header>ADOWE</header>
<title>Adowe</title>
<h1>Adowe Technologies</h1>
<body>Advertising has long been the lifeblood of commercial industry growth. Advertising campaigns have shaped popular culture, and launched brands into the public eye. The greatest campaigns are remembered long after they’ve completed their run. To grow your brands, you need to craft effective advertising campaigns. To simply put ads isn’t enough in modern times; you need to craft, manage & scale the campaign and ensure that ads are visible to the audience.
<br>Crafting campaigns like these is what drives us at AdoWe Technologies. Our mission is to help our brands leverage advertising campaigns on vehicles to build brand awareness and drive product demand. Whether you’re an established brand or a new market contender, our team can help you build through effective advertising campaigns.
<br>AdoWe Technologies is new age advertising company which can empower your brand for a data driven marketing. Our goal is to take our brand to billion Indians in a very cost effective manner.
<br>
<h1>Mobile Advertising/ Car Advertising</h1>
<br>
Mobile advertising refers to placing of adverts on any form of transportation including planes, taxis, vans and cars.
<br>Imagine your logo being viewed by countless potential customers constantly. Cars frequent the local schools and supermarkets, local roads and motorways, and regrettably get stuck in traffic jams. They are seen by millions each year. Exposure is constant and cannot be turned off or ignored. Does your current form of advertising do that for you? This is direct marketing at its best!
<br>Wrap Advertising/Vehicle Advertising is becoming one of the most effective forms of advertising to promote businesses, for both large and small businesses. When it comes to promoting your company, a vehicle wrap will give you the most impressions made per Rupee than any other form of outdoor advertising. Designing and installing a vehicle wrap will create hundreds of thousands of impressions per day, and millions in a month. With these results you are sure to increase your customer base and yearly business revenue

<h2>See you campaign</h2>
<br><a href="{%url 'oda:login'%}">Brand Login</a>

oda/templates/oda/login.html
<h1>User Login</h1>
{%if error_message %}
<p><strong>{{error_message}}</strong>>
{%endif%}
                            <form class="form-horizontal" role="form" action="{%url 'oda:login'%}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id_username">
                                        Username:
                                    </label>
                                    <div class="col-sm-10">
                                        <input id="id_username" maxlength="30" name="username" type="text">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id_password">
                                        Password:
                                    </label>
                                    <div class="col-sm-10">
                                        <input id="id_password" maxlength="30" name="password" type="password">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>

oda/templates/oda/map_point.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Campaign</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
      #floating-panel {
        background-color: #fff;
        border: 1px solid #999;
        left: 25%;
        padding: 5px;
        position: absolute;
        top: 10px;
        z-index: 5;
      }
    </style>
  </head>

  <body>
    <div id="floating-panel">
      <button onclick="toggleHeatmap()">Toggle Heatmap</button>
      <button onclick="changeGradient()">Change gradient</button>
      <button onclick="changeRadius()">Change radius</button>
      <button onclick="changeOpacity()">Change opacity</button>
    </div>
    <div id="map"></div>
    <script>

      // This example requires the Visualization library. Include the libraries=visualization
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=visualization">

      var map, heatmap;

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: {lat: 22.592714, lng: 88.394888},
          mapTypeId: 'satellite'
        });

        heatmap = new google.maps.visualization.HeatmapLayer({
          data: getPoints(),
          map: map
        });
      }

      function toggleHeatmap() {
        heatmap.setMap(heatmap.getMap() ? null : map);
      }

      function changeGradient() {
        var gradient = [
          'rgba(0, 255, 255, 0)',
          'rgba(0, 255, 255, 1)',
          'rgba(0, 191, 255, 1)',
          'rgba(0, 127, 255, 1)',
          'rgba(0, 63, 255, 1)',
          'rgba(0, 0, 255, 1)',
          'rgba(0, 0, 223, 1)',
          'rgba(0, 0, 191, 1)',
          'rgba(0, 0, 159, 1)',
          'rgba(0, 0, 127, 1)',
          'rgba(63, 0, 91, 1)',
          'rgba(127, 0, 63, 1)',
          'rgba(191, 0, 31, 1)',
          'rgba(255, 0, 0, 1)'
        ]
        heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
      }

      function changeRadius() {
        heatmap.set('radius', heatmap.get('radius') ? null : 20);
      }

      function changeOpacity() {
        heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
      }

      // Heatmap data: 500 Points
      
      function getPoints() {
        return [
        {%for dat in data%}
          new google.maps.LatLng({{dat.latpos}}, {{dat.lonpos}}),
          
        {%endfor%}
        ];
      }
      
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqQk95yb7uMTwezjUiQIHdkRl2D6lGNwQ&libraries=visualization&callback=initMap">
    </script>
  </body>
</html>

oda/templates/oda/register.html
<h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%include 'oda/form_template'%}
                        <div class="form-group">
                        	<div class="col-sm-offset-2-col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
					</form>

oda/templates/oda/registration_form.html
<h1>User Login</h1>
{%if error_message %}
<p><strong>{{error_message}}</strong>>
{%endif%}
                            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id_username">
                                        Username:
                                    </label>
                                    <div class="col-sm-10">
                                        <input id="id_username" maxlength="30" name="username" type="text">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id_password">
                                        Password:
                                    </label>
                                    <div class="col-sm-10">
                                        <input id="id_password" maxlength="30" name="password" type="password">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>